server:
  port: 9099

mitocode:
  security:
    key: a83425b983bec6b040197c9a88a366c6ee2f3243a297f656a4fb1ca2b4cdea17


# Mongo Configuration
spring:
  data:
    mongodb:
      uri: mongodb://mitocode:mitocode@localhost:27017/mitocode?authSource=admin

management:
  endpoints:
    web:
      base-path: /actuator         # default, solo para dejar claro
      exposure:
        include: health,info,mappings,env,beans,configprops,loggers
  endpoint:
    health:
      show-details: always         # útil en dev
