server:
  port: 9099

mitocode:
  security:
    key: mitocode-secret


# Mongo Configuration
spring:
  data:
    mongodb:
      uri: mongodb://mitocode:mitocode@localhost:27017/mitocode?authSource=admin