mitocode:
  course:
    environment: qa
    instructor: Jonathan Choy
    description: Curso de Microservicios con Spring Boot y Spring Cloud
    password: '{cipher}d864a3725c55ea5b24ff4ed224cdf53a8b6b176e356d5773ca98b3340bf83f59'